services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 4003:4200
    volumes:
      - /app/node_modules
      - ./api:/app
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
  mongo:
    volumes:
      - ./mongo/data/db:/data/db
